[package]
name = "static_site_generator"
version = "0.1.0"
authors = ["Jason Brooks <cs.jasonbrooks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "0.3"
